ALTER TABLE [Audit].[AuditPackageMaster]
    ADD CONSTRAINT [PK_AuditPackageMaster] PRIMARY KEY CLUSTERED ([MasterKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

