ALTER TABLE [DW].[DimVehicleMakeModel]
    ADD CONSTRAINT [PK_DimVehicleMakeModel] PRIMARY KEY CLUSTERED ([VehicleMakeModelKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

