ALTER TABLE [DW].[DimRepoAge]
    ADD CONSTRAINT [PK_DimRepoAge] PRIMARY KEY CLUSTERED ([RepoAgeKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

