ALTER TABLE [DW].[DimStorageLocation]
    ADD CONSTRAINT [PK_DimStorageLocation] PRIMARY KEY CLUSTERED ([StorageLocationKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

