ALTER TABLE [DW].[DimRecoveryAgent]
    ADD CONSTRAINT [PK_DimRecoveryAgent] PRIMARY KEY CLUSTERED ([RecoveryAgentKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

