ALTER TABLE [DW].[DimBorrower]
    ADD CONSTRAINT [PK_DimBorrower] PRIMARY KEY CLUSTERED ([BorrowerKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

