ALTER TABLE [DW].[DimCalendar]
    ADD CONSTRAINT [PK_DimCalendar] PRIMARY KEY CLUSTERED ([CalendarKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

