ALTER TABLE [DW].[DimCaseWorker]
    ADD CONSTRAINT [PK_DimCaseWorker] PRIMARY KEY CLUSTERED ([CaseWorkerKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

