ALTER TABLE [DW].[DimAdjuster]
    ADD CONSTRAINT [PK_DimAdjuster] PRIMARY KEY CLUSTERED ([AdjusterKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

