ALTER TABLE [DW].[DimRepoStatus]
    ADD CONSTRAINT [PK_DimRepoStatus] PRIMARY KEY CLUSTERED ([RepoStatusKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

