ALTER TABLE [DW].[DimRepoDetails]
    ADD CONSTRAINT [PK_DimRepoDetails] PRIMARY KEY CLUSTERED ([RepoDetailsKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

