ALTER TABLE [DW].[DimLienHolder]
    ADD CONSTRAINT [PK_DimLienHolder] PRIMARY KEY CLUSTERED ([LienHolderKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

