ALTER TABLE [DW].[DimClient]
    ADD CONSTRAINT [PK_DimClient] PRIMARY KEY CLUSTERED ([ClientKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

