ALTER TABLE [DW].[DimAddress]
    ADD CONSTRAINT [PK_DimAddress] PRIMARY KEY CLUSTERED ([AddressKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

