ALTER TABLE [DW].[DimDisposition]
    ADD CONSTRAINT [PK_DimDisposition] PRIMARY KEY CLUSTERED ([DispositionKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

