ALTER TABLE [DW].[FactRepo]
    ADD CONSTRAINT [PK_FactRepo] PRIMARY KEY CLUSTERED ([FactRepoKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

